apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: user-roles
spec:
  deletionPolicy: Delete
  forProvider:
    realmIdRef:
      name: "dev"
    roleIdsRefs:
      - name: test
    userIdRef:
      name: "tim-tester"
  providerConfigRef:
    name: "keycloak-provider-config"