apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Permissions
metadata:
  name: my-user-permission
  namespace: dev
spec:
  deletionPolicy: Delete
  forProvider:
    realmIdRef:
      name: "dev"
  providerConfigRef:
    name: "keycloak-provider-config"
