apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: test-members
spec:
  deletionPolicy: Orphan
  forProvider:
    groupIdRef:
      name: test
    members:
      - bree
    realmId: dev
  providerConfigRef:
    name: "keycloak-provider-config"