apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Permissions
metadata:
  name: my-group-permission
  namespace: dev
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: "dev"
    groupIdRef:
      name: "test"
  providerConfigRef:
    name: "keycloak-provider-config"
