apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: DefaultGroups
metadata:
  name: my-default-groups
spec:
  deletionPolicy: Delete
  forProvider:
    groupIdsRefs:
      - name: test
    realmIdRef:
      name: "dev"
  providerConfigRef:
    name: "keycloak-provider-config"