---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: test-client
  namespace: upbound-system
spec:
  forProvider:
    realmId: "dev"
    name: "abc"
    clientIdRef:
      name: "test"
    description: "abc"
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the provider configuration